### ISSUE TITLE
RFC: I'm thinking of turning this into a random dns querier

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/RuinMyHistory#10]
Since the project's release, I've had a lot more interest than I expected. A few people seem to be semi-seriously using it, and the current list of nearly 500 sites isn't working. Some of the sites are giving people notification warnings (like sedoparking that was there a while back). Not to mention it's a finite list.

What I'd like to propose is that instead of this tool having a fixed list of sites, that it instead uses xmlhttprequest or some other api to generate dns queries. What I would be doing is to hook up a random string generator to an api like xmlhttprequest. Almost all of the requests would be failing ones, but the requests would be junk ones (not as helpful as real sites for hiding what you're doing).

Alternatively, I could explore ways of people adding their own site lists along with the default site.

I can tell people are interested in this, and I don't want to up and leave the project in its current state since it can be expanded upon. At the same time, I'm not sure what to do, and I don't have a great deal of time to put into this project now.

**Comment by windykestrel** [comment]
I think allowing users to add and build upon their own site lists may be closer to what most of us are looking for-- a way to pollute our data. I'd definitely be interested in a tool that allowed for more customisation.

**Comment by FascinatedBox** [comment]
I ended up completely forgetting that I even made this. A few days after making it, I lost most of the interest I had in it, since I didn't think anyone was using it. It ended up being more popular than I expected, so I'll keep it around. I don't intend to do any further updates to it though.
