### ISSUE TITLE
More sites

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/RuinMyHistory#5]
For this to work in any kind of capacity, there need to be more websites added. I don't visit a lot of pages, but that's where other people can pitch in. You can add whatever, as long as:

* Domains aren't repeated.
* No objectionable content. I realize this is about polluting people's history, but "this could get you on a list" kind of content is a no-no.
* No popups or resource-heavy javascript/css/whatever
* Please don't send a commit adding like over 9000 sites at once.

**Comment by devonparsons** [comment]
You should consider taking advantage of some websites 'random content' features, like reddit's /r/random subreddit - or, support a list of specific URLS per site to make it look like we are ACTUALLY viewing the content, and not just the front page.

**Comment by drifterr** [comment]
You should also consider having the page follow several links on the page, at least a few links deep. This would simulate an average person's browsing style and make it harder to filter signal from noise. If the links remain on the same site or that of an approved domain, security should be reasonable.

**Comment by FascinatedBox** [comment]
I'm closing this because this project was made as a fun distraction. Many of the ideas posed are well beyond what I had in mind for this project, which was initially made to be "make a bunch of dns queries to valid sites".
